default:
  - build

build:
  - clean:default
  - jshint:lib
  - lintspaces:lib
  - concat
  - uglify

build:docs:
  - clean:docs
  - jsdoc

prerelease:
  - build:docs
  - gitcommit:docs
  - build
  - gitcommit:build

updateVersion:patch:
  - prerelease
  # TODO: Changelog creation
  - release:patch

updateVersion:minor:
  - prerelease
  - release:minor

updateVersion:major:
  - prerelease
  - release:major
